<?php
include('connection.php');

date_default_timezone_set('Asia/Manila');
$todayDate = date("F j, Y : g:i A");
$timeApproved = date('Y-m-d h:i:s');

$addUserId   = $_POST['addUserId'] ?? '';
$addEmpId    = $_POST['addEmpId'] ?? '';
$fullName    = $_POST['namee'] ?? '';
$addBranch   = $_POST['addBranch'] ?? '';
$addEmail    = $_POST['addEmail'] ?? '';
$addToEmail  = $_POST['addToEmail'] ?? '';
$addCategory = $_POST['addCategory'] ?? '';
$addKindOfDay = $_POST['addKindOfDay'] ?? '';
$addDateFrom = $_POST['addDateFrom'] ?? '';
$addDateTo   = $_POST['addDateTo'] ?? '';
$addTimeFrom = $_POST['addTimeFrom'] ?? '';
$addTimeTo   = $_POST['addTimeTo'] ?? '';
$addMessage   = $_POST['addMessage'] ?? '';

$approver = 'Generated by: System';
$iStatus = 2;
$iAbsent = 1;

$vl = 0;
$sl = 0;
$ml = 0;
$el = 0;
$ul = 0;

if ($addDateFrom && $addDateTo) {
    $from = new DateTime($addDateFrom);
    $to   = new DateTime($addDateTo);
    $diff = $from->diff($to)->days + 1;

    // echo $diff; 
}

function number_of_working_days($startDate, $endDate){
  $workingDays = 0;
  $startTimestamp = strtotime($startDate);
  $endTimestamp = strtotime($endDate);

  for ($i = $startTimestamp; $i <= $endTimestamp; $i += 86400) {
      if (date("N", $i) <= 5) {
          $workingDays++;
      }
  }
  return $workingDays;
}

function number_of_weekend_days($startDate, $endDate){
  $weekendDays = 0;
  $startTimestamp = strtotime($startDate);
  $endTimestamp = strtotime($endDate);

  for ($i = $startTimestamp; $i <= $endTimestamp; $i += 86400) {
      if (date("N", $i) > 5) {
          $weekendDays++;
      }
  }
  return $weekendDays;
}

$startDate = date('Y-m-d', strtotime($addDateFrom));
$endDate   = date('Y-m-d', strtotime($addDateTo));
$workingDays = number_of_working_days($startDate, $endDate);

if ($addKindOfDay == 'Half Day' && $startDate == $endDate) {
  $workingDays *= 0.5;
  $diff = 0.5;
}

if($addCategory == 'Vacation Leave'){
  $vl = $diff;
}else if($addCategory == 'Sick Leave'){
  $sl = $diff;
}else if($addCategory == 'Mandatory Leave'){
  $ml = $diff;
}else if($addCategory == 'Emergency Leave'){
  $el = $diff;
}else if($addCategory == 'Unpaid Leave'){
  $ul = $diff;
}else{
  $vl = 0;
  $sl = 0;
  $ml = 0;
  $el = 0;
  $ul = 0;
}

if($addCategory === 'Official Business'){
  $addKindOfDay = '';
  $workingDays = 0;
}

$sql = "INSERT INTO `leavetbl` 
                              (`user_Id`, `employee_Id`, `iName`, `iBranch`, `myDate`, `iEmail`, `toEmail`, 
                              `iCategory`, `dateFrom`, `dateTo`, `timeFrom`, `timeTo`, `workingDays`, 
                              `kindDay`, `iMessage`, `approver`, `timeApproved`, `iStatus`, `iAbsent`)
                        VALUES 
                              (?, ?, ?, ?, ?, ?, ?, 
                                ?, ?, ?, ?, ?, ?, 
                                ?, ?, ?, ?, ?, ?)
        ";

$stmt = $con->prepare($sql);

$stmt->bind_param(
                  "iissssssssssdssssii", 
                  $addUserId, $addEmpId, $fullName, $addBranch, $todayDate, $addEmail, $addToEmail, 
                  $addCategory, $addDateFrom, $addDateTo, $addTimeFrom, $addTimeTo, 
                  $workingDays, $addKindOfDay, $addMessage, $approver, $timeApproved, $iStatus, $iAbsent
                );

if(!$stmt->execute()) {
    echo "Inserting Error: " . $stmt->error;
} else {
    $stmtUpdate = "UPDATE accounts SET `VL` = VL - ?, `SL` = SL - ?, `ML` = ML - ?, `EL` = EL - ?, `UL` = UL + ? WHERE userId = ?";
    $stmtUpdate = $con->prepare($stmtUpdate);
    $stmtUpdate->bind_param('dddddi', $vl, $sl, $ml, $el, $ul, $addUserId);
    if($stmtUpdate->execute()) {
      echo json_encode(['success' => true, 'message' => 'Leave Added Successfully!']);
    }else{
      echo json_encode(['success' => false, 'message' => 'Failed to Update Leave Count!' . $stmtUpdate->error]);
    }
}
$stmtUpdate->close();
$stmt->close();
$con->close();
