<?php 
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'phpMailer/src/Exception.php';
require 'phpMailer/src/PHPMailer.php';
require 'phpMailer/src/SMTP.php';

include('connection.php');
include('fileupload.php');

    date_default_timezone_set('Asia/Manila');
    $dateToday = date('F j, Y \a\t g:i A');
    $selectedBranch = $_POST['selectBranch'];
    $selectedRequest = $_POST['selectRequestType'];

    $userId = 10001; //dummy user
    $empId = 10001; //dummy emp. id
    $name = 'Dashboard System Importer'; // dummy name
    $position = 'IT Support'; // dummy position
    $status = 4; // Approved

    switch ($selectedBranch) {
        case 'Ternate':
            $department = 12;
            $fromEmail = 'melody.ruazol@ourbank.ph';
            break;
        case 'Poblacion':
            $department = 10;
            $fromEmail = 'jacklyn.sarique@ourbank.ph';
            break;
        case 'Maragondon':
            $department = 14;
            $fromEmail = 'ednalyn.paraiso@ourbank.ph';
            break;
        case 'Manggahan':
            $department = 11;
            $fromEmail = 'jennifer.giron@ourbank.ph';
            break;
        case 'Magallanes':
            $department = 13;
            $fromEmail = 'joan.reduca@ourbank.ph';
            break;
        case 'Noeveleta':
            $department = 9;
            $fromEmail = 'karen.dianne.dampitan@ourbank.ph';
            break;
        default:
            $department = 8;
            $fromEmail = 'ritchie.arcilla@ourbank.ph';
            break;
    }

    $toEmail = 'helpdesk@ourbank.ph';
    $requestImport = $_FILES['requestImport'];
    $file =  upload_file($requestImport, 'request');
    $approver = 'Generated By: System';

    $todayDate = date('Y-m-d');
    // $sqlAbsent = "SELECT a.userDepartment, l.* FROM `accounts` as a
        //               JOIN `department` as d ON d.id = a.userDepartment
        //               JOIN `leavetbl` as l ON l.user_Id = a.userId
        //               WHERE l.iBranch = '" . $_SESSION['address'] . "'
        //               AND a.userDepartment  = '" . $_SESSION['department'] . "'
        //               AND dateFrom = '$todayDate'
        //               AND user_Id IN (9, 10, 12, 15, 17, 25, 30)"; //71, 73, 75, 77, 79, 81, 83 -- dummy bm in database to login
        // $queryAbsent = mysqli_query($con, $sqlAbsent);
        // $rowFetch = mysqli_fetch_assoc($queryAbsent);

        // Check for keyword "dummy" in request
        // if (stripos($r_Request, 'dummy') !== false) {
        //     $r_Status = 1;
        // } else if(stripos($r_Request, 'write-off') !== false) {
        //     $r_Status = 1;
        // } else {
        //     if ($rowFetch['iAbsent'] == 1 && $rowFetch['dateFrom'] == $todayDate && $rowFetch['iStatus'] == 2) {
        //         if ($_SESSION['bankposition'] == 'Branch Cashier') {
        //             $r_Status = 1;
        //         }
        //     } else {
        //         if (!empty($rowFetch) || empty($rowFetch)) {
        //             if ($_SESSION['position'] == 'Staff') {
        //                 $r_Status = 0;
        //             } else {
        //                 $r_Status = 6;
        //             }
        //         }
        //     }
        // }

    if(!empty($file['result']) || empty($file['result'])) {
      $destination = $file['path'];
        $sqlInsert = "INSERT INTO `request` (`r_user_Id`, `r_employee_Id`, `r_Name`, `r_Branch`, `r_myDate`, `r_Email`, `r_toEmail`, `r_Position`, `r_userDepartment`, `r_Request`, `r_Status`, `r_Image`, `r_approver`) 
                  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        $stmt = $con->prepare($sqlInsert);
        $stmt->bind_param("iissssssisiss", $userId, $empId, $name, $selectedBranch, $dateToday, $fromEmail, $toEmail, $position, $department, $selectedRequest, $status, $destination, $approver);

        if($stmt->execute()){
          // insert condition here if absent bm/head ()=> gm/agm
              // $sessionEmail = $_SESSION['useremail'];
              // $sessionName = $_SESSION['fullname'];
              // $r_toEmail = $_POST['r_toEmail'];

              // $urlink = '<a target="_blank" href="https://10.10.10.120/dashboard/">OUR Bank Dashboard</a>';
              // $filename = 'request2.jpg';
              // $cid = 'my-attach';
              // $subject = 'Requesting IT Support';

              // $mail = new PHPMailer(true);    
                        
              // $mail -> isSMTP();
              // // $mail -> Host = 'smtp.gmail.com';
              // $mail -> Host = 'ourbank.ph';
              // $mail -> SMTPAuth = true;
              // // $mail -> Username = 'ourbanktech@gmail.com';
              // // $mail -> Password = 'pcgafzbvjwusqunp';
              // $mail -> Username = 'helpdesk@ourbank.ph';
              // $mail -> Password = '0urb@nk-2021';
              // // $mail -> Username = 'ctborgonia@ourbank.ph';
              // // $mail -> Password = 'Tp043094r$';
              // $mail -> SMTPSecure = 'ssl';
              // $mail -> Port = 465;
              // $mail->AddEmbeddedImage("request2.jpg", "my-attach", "request2.jpg");
                        
              // $mail->addEmbeddedImage($filename, $cid);
                        
              // $mail -> setFrom($sessionEmail, $sessionName); // Sender
                            
              // // $mail -> addAddress($r_toEmail); //receiver
              // if($_SESSION['position'] == 'Staff'){
              //   $mail -> addAddress($r_toEmail); //receiver
              //   // $mail -> addAddress('ctborgonia@ourbank.ph'); //for testing receiver
              // }
              // else if($_SESSION['position'] == 'Head' || $_SESSION['position'] == 'BM' || $_SESSION['position'] == 'GM' || $_SESSION['position'] == 'AGM'){
              //   $mail -> addAddress('jcvillanueva@ourbank.ph');
              //   // $mail -> addAddress('ctborgonia@ourbank.ph'); //for testing receiver
              // }
              // $mail -> isHTML(true);

              // $mail -> Subject = '[ Support ]' . $r_Branch;
                            
              // $mail -> Body = 'Please click this link to proceed: <a target="_blank" href="https://10.10.10.120/dashboard/">OUR Bank Dashboard</a>
              //                 <br>';
              // $mail -> send();
            $response['message'] = 'Successfully Added!';
            $response['result'] = true;
        }else{   
          $response['message'] = 'Something Wrong!';
        }
    }else {
        $response['message'] = $file['message'];
    }
    echo json_encode($response['message']);
?>